services:
  ros:
    build: .
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - /sys/class/pwm:/sys/class/pwm
      - /run/udev/:/run/udev/
      - ./node_connections:/node_connections
      - ./videos:/videos
    group_add:
      - video
    environment:
      - HOME=/tpm
    stdin_open: true # equivalent to -i (interactive)
    tty: true # equivalent to -t (tty)
    stop_signal: SIGINT
    stop_grace_period: 20s