services:
  ros:
    build: .
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - /sys/class/pwm:/sys/class/pwm
      - /run/udev/:/run/udev/
      - ./node_connections:/node_connections
      - ./videos:/videos
      - /lib/firmware:/lib/firmware
      - /lib/udev/rules.d:/lib/udev/rules.d
      - /lib/modules:/lib/modules
      # - ./ros_logs:/var/log/ros
    group_add:
      - video
    devices:
      - /dev/h1x-0:/dev/h1x-0
    environment:
      - DISPLAY=:0
      # - ROS_LOG_DIR=/var/log/ros
    stdin_open: true # equivalent to -i (interactive)
    tty: true # equivalent to -t (tty)
    stop_signal: SIGINT
    stop_grace_period: 20s
    restart: unless-stopped
    command: 
    - ros2 
    - launch 
    - robot_core
    - comp.launch.py
    