# Request
uint8 device_address          # I2C address of device
uint8 register_address        # Register to read from
uint8 length                  # Number of bytes to read

---
# Response
uint8[] data                  # Received data
bool success
string message                # Error message
