# Request
uint8 device_address          # I2C address of device
uint8 register_address        # Starting register
uint8[] data                  # Bytes to write

---
# Response
bool success
string message                # Error message
