state_machine:
  ros__parameters:
    line_follow_node: /line_follow/core_loop

servo_grab:
  ros__parameters:
    listen_topic: '/servo/grab'
    servo_id: 0
    gpio_pin: 4

servo_lift:
  ros__parameters:
    listen_topic: '/servo/lift'
    servo_id: 1
    gpio_pin: 0

servo_tray_release:
  ros__parameters:
    listen_topic: '/servo/tray_release'
    servo_id: 2
    gpio_pin: 1

idle_button:
  ros__parameters:
    gpio_pin: 6
    publish_topic: '/idle_button'
    pull_up: True

/pwm0:
  pwm_controller:
    ros__parameters:
      pwm_channel: 0

/pwm1:
  pwm_controller:
    ros__parameters:
      pwm_channel: 1

/pwm2:
  pwm_controller:
    ros__parameters:
      pwm_channel: 2

/front_camera:
  camera_node:
    ros__parameters:
      camera: 0
      role: 'viewfinder'
      format: 'BGR888'
      width: 1536
      height: 864
      sensor_mode: '2304:1296'
      orientation: 180

/down_camera:
  camera_node:
    ros__parameters:
      camera: 1
      role: 'viewfinder'
      format: 'BGR888'
      width: 1536
      height: 864
      sensor_mode: '2304:1296'
      orientation: 0

bno08x_driver:
  ros__parameters:
    frame_id: 'bno086' # The frame_id to use for the sensor data

    # Communication Interface
    # Select the communication interface to use
    # (only one interface can be enabled at a time)
    # This requires a hardware change to the board
    # (see documentation for more information)
    i2c:
      enabled: true
      bus: '/dev/i2c-1'
      address: '0x4A'

    publish:
      magnetic_field:
        enabled: true
        rate: 100 # max 100 Hz
      imu:
        enabled: true
        rate: 100 # max 400 Hz

twist_subscriber:
  ros__parameters:
    wheel_dist: 0.155
    counts_per_revolution: 1000.0
    wheel_radius: 0.04
    max_counts_per_second: 1800.0
    stop_delay: 0.2

odom_publisher:
  ros__parameters:
    wheel_dist: 0.155
    counts_per_revolution: 1000.0
    wheel_radius: 0.04

ekf_filter_node:
  ros__parameters:
    # The frequency, in Hz, at which the filter will output a position estimate. Note that the filter will not begin
    # computation until it receives at least one message from one of the inputs. It will then run continuously at the
    # frequency specified here, regardless of whether it receives more measurements. Defaults to 30 if unspecified.
    frequency: 30.0

    # ekf_localization_node and ukf_localization_node both use a 3D omnidirectional motion model. If this parameter is
    # set to true, no 3D information will be used in your state estimate. Use this if you are operating in a planar
    # environment and want to ignore the effect of small variations in the ground plane that might otherwise be detected
    # by, for example, an IMU. Defaults to false if unspecified.
    two_d_mode: false

    # Whether to publish the acceleration state. Defaults to false if unspecified.
    publish_acceleration: true

    # Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
    publish_tf: true

    # 1. Set the map_frame, odom_frame, and base_link frames to the appropriate frame names for your system.
    #     1a. If your system does not have a map_frame, just remove it, and make sure "world_frame" is set to the value of odom_frame.
    # 2. If you are fusing continuous position data such as wheel encoder odometry, visual odometry, or IMU data, set "world_frame"
    #    to your odom_frame value. This is the default behavior for robot_localization's state estimation nodes.
    # 3. If you are fusing global absolute position data that is subject to discrete jumps (e.g., GPS or position updates from landmark
    #    observations) then:
    #     3a. Set your "world_frame" to your map_frame value
    #     3b. MAKE SURE something else is generating the odom->base_link transform. Note that this can even be another state estimation node
    #         from robot_localization! However, that instance should *not* fuse the global data.
    odom_frame: odom # Defaults to "odom" if unspecified
    base_link_frame: base_link # Defaults to "base_link" if unspecified
    world_frame: odom # Defaults to the value of odom_frame if unspecified

    odom0: wheel/odom
    odom0_config:
      [
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ]

    imu0: imu/data
    imu0_config:
      [
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
      ]

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
