name: ROS2 Tests

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # fetch-depth: 0 is recommended if you need to access full git history
          fetch-depth: 0

      - name: Build and test ROS 2 workspace
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          # Specify the ROS 2 distribution, e.g., 'humble', 'iron', 'rolling'
          ros-distro: kilted
          # Specify the build and test arguments
          colcon-defaults: |
            {
              "build": {
                "args": "--cmake-args -DCMAKE_BUILD_TYPE=Release"
              },
              "test": {
                "args": "--packages-select follower",
                "verb-args": "--event-handlers console_cohesion+ --retest-until-fail --abort-on-error"
              }
            }
